from classes.Persona import Persona
from datetime import datetime


class Requisitoriado(Persona):
    def __init__(
        self,
        nombres,
        apellidos,
        genero,
        fecha_nacimiento,
        dni,
        nacionalidad,
        direccion,
        telefono,
        cargos,
    ):
        super().__init__(
            nombres,
            apellidos,
            genero,
            fecha_nacimiento,
            dni,
            nacionalidad,
            direccion,
            telefono,
        )
        self.cargos = cargos

    def getCargos(self):
        return self.cargos

    def setCargos(self, cargos):
        self.cargos = cargos


requisitoriado_list = [
    Requisitoriado(
        "ROBERTO CARLOS",
        "Gutierrez Garcia",
        "Hombre",
        datetime(1996, 12, 4),
        "00000000",
        "El Salvador",
        "Sin Datos",
        "Sin Datos",
        "Violación en Menor O Incapaz Continuada",
    ),
    Requisitoriado(
        "ROBERTO CARLOS",
        "CHIRI ROMERO",
        "Hombre",
        datetime(1985, 11, 10),
        "00000000",
        "Bolivia",
        "Sin Datos",
        "Sin Datos",
        "Violación",
    ),
    Requisitoriado(
        "ANTONIO JOSE",
        "DE ABREU VIDAL FILHO",
        "Hombre",
        datetime(1994, 1, 3),
        "00000000",
        "Brasil",
        "Sin Datos",
        "Sin Datos",
        "Asesinato, tentativa de asesinato, tortura física y tortura mental.",
    ),
    Requisitoriado(
        "RAFIK KEFI",
        "HANNOUN",
        "Hombre",
        datetime(1989, 5, 16),
        "00000000",
        "Francia",
        "Sin Datos",
        "Sin Datos",
        "INCUMPLIMIENTO DE OBLIGACIÓN",
    ),
    Requisitoriado(
        "MARIUSZ",
        "PRZYSIUDA",
        "Hombre",
        datetime(1971, 4, 2),
        "00000000",
        "Polonia",
        "Sin Datos",
        "Sin Datos",
        "participación en el comercio de cantidades significativas de una sustancia psicotrópica",
    ),
    Requisitoriado(
        "ROSANGELA APARECIDA",
        "RIBEIRO",
        "Mujer",
        datetime(1976, 7, 18),
        "00000000",
        "Brasil",
        "Sin Datos",
        "Sin Datos",
        "Tentativa de asesinato",
    ),
    Requisitoriado(
        "DANIEL PATRICIO",
        "GOROSITO PEREZ",
        "Hombre",
        datetime(1983, 3, 22),
        "00000000",
        "Bolivia",
        "Sin Datos",
        "Sin Datos",
        "ASESINATO",
    ),
    Requisitoriado(
        "RRABIE",
        "RIFFI",
        "Hombre",
        datetime(1986, 2, 10),
        "00000000",
        "Argelia",
        "Sin Datos",
        "Sin Datos",
        "ARRESTAMIENTO, SECUESTRO, DETENCIÓN ABSTRACTA O ARBITRARIA COMETIDOS EN PANDILLA ORGANIZADA",
    ),
    Requisitoriado(
        "EDWIN ALFREDO",
        "ESPINOZA CONDORI",
        "Hombre",
        datetime(1989, 11, 17),
        "00000000",
        "Bolivia",
        "Sin Datos",
        "Sin Datos",
        "VIOLACION - DELITOS SEXUALES",
    ),
    Requisitoriado(
        "TULIO DE JESUS",
        "PINTO GONZALEZ",
        "Hombre",
        datetime(1995, 10, 10),
        "00000000",
        "Guatemala",
        "Sin Datos",
        "Sin Datos",
        "PLAGIO O SECUESTRO Y ASESINATO",
    ),
    Requisitoriado(
        "JOSE DAVID",
        "ZEAS MENDOZA",
        "Hombre",
        datetime(1998, 12, 4),
        "00000000",
        "Nicaragua",
        "Sin Datos",
        "Sin Datos",
        "SECUESTRO EXTORSIVO,ROBO AGRAVADO, TENENCIA ILEGAL DE ARMAS DE FUEGO O MUNICIONES",
    ),
    Requisitoriado(
        "JOSE IVAN",
        "HERNANDEZ CASTRO",
        "Hombre",
        datetime(2001, 5, 25),
        "00000000",
        "Nicaragua",
        "Sin Datos",
        "Sin Datos",
        "SECUESTRO EXTORSIVO, ROBO AGRAVADO, PORTACION ILEGAL DE ARMAS DE FUEGO O MUNICIONES",
    ),
    Requisitoriado(
        "ELSON",
        "DE CARVALHO MELO QUIRINO DE MORAIS",
        "Hombre",
        datetime(1980, 5, 2),
        "00000000",
        "Brasil",
        "Sin Datos",
        "Sin Datos",
        "Trapacero",
    ),
    Requisitoriado(
        "KAPIL",
        "SANGWAN",
        "Hombre",
        datetime(1994, 11, 10),
        "00000000",
        "India",
        "Sin Datos",
        "Sin Datos",
        "ASESINATO, INTENTO DE ASESINATO",
    ),
    Requisitoriado(
        "VIKRAMJEET",
        "SINGH",
        "Hombre",
        datetime(1990, 6, 6),
        "00000000",
        "India",
        "Sin Datos",
        "Sin Datos",
        "Allanamiento de morada para cometer un delito punible con la muerte",
    ),
    Requisitoriado(
        "MISRAEL",
        "CARDONA CABRERA",
        "Hombre",
        datetime(1978, 11, 11),
        "00000000",
        "Guatemala",
        "Sin Datos",
        "Sin Datos",
        "Violación",
    ),
    Requisitoriado(
        "JOSE ARMANDO",
        "ABREGO FUENTES",
        "Hombre",
        datetime(1998, 4, 26),
        "00000000",
        "El Salvador",
        "Sin Datos",
        "Sin Datos",
        "Homicidio Agravado",
    ),
    Requisitoriado(
        "VICTOR MANUEL",
        "CORTEZ LOPEZ",
        "Hombre",
        datetime(1974, 3, 10),
        "00000000",
        "Nicaragua",
        "Sin Datos",
        "Sin Datos",
        "HOMICIDIO",
    ),
    Requisitoriado(
        "MELVIN JOSSUE",
        "ANGEL FLORES",
        "Hombre",
        datetime(1997, 5, 6),
        "00000000",
        "El Salvador",
        "Sin Datos",
        "Sin Datos",
        "Homicidio Agravado.",
    ),
    Requisitoriado(
        "JAIME AMILCAR",
        "GUEVARA PAZ",
        "Hombre",
        datetime(1976, 11, 8),
        "00000000",
        "El Salvador",
        "Sin Datos",
        "Sin Datos",
        "Extorsión Agravada",
    ),
    Requisitoriado(
        "OSCAR ANTONIO",
        "ESCOBAR SÁNCHEZ",
        "Hombre",
        datetime(1985, 12, 2),
        "00000000",
        "El Salvador",
        "Sin Datos",
        "Sin Datos",
        "Organizaciones Terroristas",
    ),
    Requisitoriado(
        "AURELIO",
        "IBARRA MARTINEZ",
        "Hombre",
        datetime(1956, 6, 16),
        "00000000",
        "Bolivia",
        "Sin Datos",
        "Sin Datos",
        "Violación",
    ),
    Requisitoriado(
        "JOSE ABDON",
        "MENDOZA BELTRAN",
        "Hombre",
        datetime(1980, 1, 10),
        "00000000",
        "Bolivia",
        "Sin Datos",
        "Sin Datos",
        "Lesiones con resultado de muerte homicidio o asesinato",
    ),
    Requisitoriado(
        "ABDELKADER",
        "BOUGUETTAIA",
        "Hombre",
        datetime(1987, 6, 29),
        "00000000",
        "Francia",
        "Sin Datos",
        "Sin Datos",
        "PARTICIPACIÓN EN UNA ASOCIACIÓN DE CRIMINALES",
    ),
]

print(len(requisitoriado_list))
